#Requires -Version 7.2
<#
    InvokeBuild tasks for PSGraphRenderToHtml.

    Five tasks by name: Clean, Lint, Build, Test, PreTag. The default declares
    exactly Clean, Lint, Build, Test - PreTag is deliberately outside it, so a
    half-finished iteration can still run a green build while the tag cannot.
#>

$ModuleName = 'PSGraphRenderToHtml'
$SrcRoot = Join-Path $BuildRoot "src/$ModuleName"
$OutRoot = Join-Path $BuildRoot "output/$ModuleName"
$TestsRoot = Join-Path $BuildRoot 'tests'
$AnalyzerSettings = Join-Path $BuildRoot 'PSScriptAnalyzerSettings.psd1'

task Clean {
    $output = Join-Path $BuildRoot 'output'
    if (Test-Path -LiteralPath $output) {
        Remove-Item -LiteralPath $output -Recurse -Force
    }
}

task ResolveRenderer {
    # Finding a module is not the same as finding the right one. A resolution
    # step that checks a path exists and stops is a step that cannot fail.
    $manifestPath = Join-Path $SrcRoot "$ModuleName.psd1"
    $manifest = Import-PowerShellDataFile -LiteralPath $manifestPath

    $name = 'PSGraphRender'
    $declared = @($manifest.RequiredModules | Where-Object {
            $_ -is [System.Collections.IDictionary] -and $_['ModuleName'] -eq $name
        })
    if ($declared.Count -ne 1) {
        throw "The manifest declares $($declared.Count) RequiredModules entries for '$name'. The version this build resolved cannot be checked against a requirement that is not there."
    }

    $resolved = Resolve-RendererPath -Name $name
    $found = [version](Import-PowerShellDataFile -LiteralPath $resolved).ModuleVersion

    # Every constraint RequiredModules CAN express, not the one written today.
    # A requirement that stops being checked when its shape changes is a
    # requirement nobody is checking.
    $requirement = $declared[0]
    foreach ($key in 'RequiredVersion', 'ModuleVersion', 'MaximumVersion') {
        if (-not $requirement.Contains($key)) { continue }
        $want = [version]$requirement[$key]
        $ok = switch ($key) {
            'RequiredVersion' { $found -eq $want }
            'ModuleVersion' { $found -ge $want }
            'MaximumVersion' { $found -le $want }
        }
        if (-not $ok) {
            throw "$name at $resolved is $found, which does not satisfy $key = $want."
        }
    }

    # Out loud, so the fact sits next to the failure rather than three tasks
    # away from it. This is the floor-not-a-pin hazard PSGraphRender's own
    # handoff names: ModuleVersion accepts everything above it.
    Write-Build Green "  ${name}: $found at $resolved"
    $script:RendererManifest = $resolved
}

function Resolve-RendererPath {
    <#
    .SYNOPSIS
        Where PSGraphRender is, by explicit path or sibling checkout.
    #>
    param([Parameter(Mandatory)] [string] $Name)

    if ($env:PSGRAPHRENDER_MODULE_PATH) {
        $candidate = $env:PSGRAPHRENDER_MODULE_PATH
        if (Test-Path -LiteralPath $candidate -PathType Container) {
            $candidate = Join-Path $candidate "$Name.psd1"
        }
        if (-not (Test-Path -LiteralPath $candidate)) {
            throw "PSGRAPHRENDER_MODULE_PATH is set to '$env:PSGRAPHRENDER_MODULE_PATH' and no $Name.psd1 was found there."
        }
        return (Resolve-Path -LiteralPath $candidate).Path
    }

    $sibling = Join-Path (Split-Path -Parent $BuildRoot) "$Name/src/$Name/$Name.psd1"
    if (Test-Path -LiteralPath $sibling) { return (Resolve-Path -LiteralPath $sibling).Path }

    $installed = Get-Module -ListAvailable -Name $Name | Sort-Object Version -Descending | Select-Object -First 1
    if ($installed) { return $installed.Path }

    throw "$Name was not found. Set PSGRAPHRENDER_MODULE_PATH, check out $Name beside this repository, or install it."
}

task Lint {
    $findings = @(Invoke-ScriptAnalyzer -Path $SrcRoot -Recurse -Settings $AnalyzerSettings)
    # PSReviewUnusedParameter is excluded for tests ONLY, and only here rather
    # than in the settings file, so it still guards src/. A Pester container
    # file's param() block is consumed inside BeforeAll/It scriptblocks, which
    # the analyzer cannot see through: it reports GraphPath as unused in the
    # battery, where GraphPath is the entire point of the file.
    $findings += @(Invoke-ScriptAnalyzer -Path $TestsRoot -Recurse -Settings $AnalyzerSettings `
            -ExcludeRule PSReviewUnusedParameter)
    if ($findings) {
        $findings | Format-Table -AutoSize | Out-String | Write-Host
        throw "PSScriptAnalyzer reported $($findings.Count) finding(s)."
    }
}

task Build Clean, ResolveRenderer, {
    $null = New-Item -ItemType Directory -Path $OutRoot -Force

    $sb = [System.Text.StringBuilder]::new()
    $null = $sb.AppendLine('# This file is auto-generated by the build. Do not edit.')
    $null = $sb.AppendLine('$script:ModuleRoot = $PSScriptRoot')
    $null = $sb.AppendLine('')

    $private = @(Get-ChildItem -LiteralPath (Join-Path $SrcRoot 'Private') -Filter *.ps1 -Recurse -File |
            Sort-Object FullName)
    $public = @(Get-ChildItem -LiteralPath (Join-Path $SrcRoot 'Public') -Filter *.ps1 -File |
            Sort-Object Name)

    foreach ($file in ($private + $public)) {
        $null = $sb.AppendLine((Get-Content -LiteralPath $file.FullName -Raw))
        $null = $sb.AppendLine('')
    }

    # Emitted as a real call listing real string constants. A generated file is
    # the one place a commented-out line is cheapest to write by accident.
    $names = $public.BaseName
    $null = $sb.AppendLine("Export-ModuleMember -Function $(($names | ForEach-Object { "'$_'" }) -join ', ')")

    Set-Content -LiteralPath (Join-Path $OutRoot "$ModuleName.psm1") -Value $sb.ToString() -Encoding utf8NoBOM
    Copy-Item -LiteralPath (Join-Path $SrcRoot "$ModuleName.psd1") -Destination $OutRoot -Force

    # The contract travels with the module: Test-ProducerGraph resolves it from
    # $script:ModuleRoot, and a module that cannot find its own schema is a
    # module whose validation silently stops validating.
    $contractOut = Join-Path $OutRoot 'contract'
    $null = New-Item -ItemType Directory -Path $contractOut -Force
    Copy-Item -LiteralPath (Join-Path $BuildRoot 'contract/producer-graph.schema.json') -Destination $contractOut -Force

    $manifest = Import-PowerShellDataFile -LiteralPath (Join-Path $SrcRoot "$ModuleName.psd1")
    $declaredCount = @($manifest.FunctionsToExport).Count
    if ($declaredCount -ne $names.Count) {
        throw "The manifest exports $declaredCount function(s) and Public/ holds $($names.Count). They are the same set or they are a bug."
    }
    foreach ($name in $names) {
        if ($name -notin $manifest.FunctionsToExport) {
            throw "Public/$name.ps1 exists and the manifest does not export '$name'."
        }
    }

    Write-Build Green "  built $ModuleName $($manifest.ModuleVersion) -> $OutRoot"
}

task Test Build, {
    $cfg = New-PesterConfiguration
    $cfg.Run.Path = $TestsRoot
    # Throw, not Exit: Run.Exit makes Pester call exit, which can terminate the
    # host process running the build.
    $cfg.Run.Throw = $true
    $cfg.Run.PassThru = $true
    # An It whose -ForEach collection is empty is INAPPLICABLE, not fatal. Left
    # at the default one such It aborts its whole container and takes every
    # assertion that had already passed with it.
    $cfg.Run.FailOnNullOrEmptyForEach = $false
    $cfg.Output.Verbosity = 'Detailed'
    $cfg.Should.DisableV5 = $true
    $cfg.Filter.ExcludeTag = 'PreTag'
    $cfg.CodeCoverage.Enabled = $true
    $cfg.CodeCoverage.Path = Join-Path $OutRoot "$ModuleName.psm1"
    $cfg.CodeCoverage.CoveragePercentTarget = 75
    # Into output/, which Clean removes and .gitignore excludes. Left at its
    # default this writes coverage.xml into the current directory - a stray
    # artifact at the repository root is one blind `git add -A` away from being
    # committed, which is how it has happened before.
    $cfg.CodeCoverage.OutputPath = Join-Path $BuildRoot 'output/coverage.xml'
    $cfg.TestResult.Enabled = $true
    $cfg.TestResult.OutputPath = Join-Path $BuildRoot 'output/testResults.xml'

    $env:PSModulePath = (Join-Path $BuildRoot 'output') + [System.IO.Path]::PathSeparator + $env:PSModulePath

    $result = Invoke-Pester -Configuration $cfg

    # CoveragePercentTarget only REPORTS. This throw is the gate, and it reads
    # the threshold back off the result rather than keeping a second copy of the
    # number - two thresholds in two places drift, and the drift is silent
    # because both halves keep working.
    $coverage = $result.CodeCoverage
    if ($coverage) {
        $percent = [math]::Round($coverage.CoveragePercent, 2)
        $target = $coverage.CoveragePercentTarget
        if ($percent -lt $target) {
            throw "Line coverage $percent% is below the target of $target%. Raise coverage, or lower the target deliberately and say so."
        }
        Write-Build Green "Line coverage: $percent% (target $target%)"
    }
}

task PreTag Build, {
    # Seals on a FINISHED iteration, deliberately outside the default task.
    $cfg = New-PesterConfiguration
    $cfg.Run.Path = $TestsRoot
    $cfg.Run.Throw = $true
    $cfg.Run.PassThru = $true
    $cfg.Run.FailOnNullOrEmptyForEach = $false
    $cfg.Should.DisableV5 = $true
    $cfg.Filter.Tag = 'PreTag'
    $cfg.Output.Verbosity = 'Detailed'

    $env:PSModulePath = (Join-Path $BuildRoot 'output') + [System.IO.Path]::PathSeparator + $env:PSModulePath
    $result = Invoke-Pester -Configuration $cfg

    # A filtered run that selected nothing graded nothing. TotalCount counts
    # tests DISCOVERED - discovery walks the whole tests/ path before the tag
    # filter applies - so it is never zero and a guard written against it can
    # never fire.
    if (($result.PassedCount + $result.FailedCount) -eq 0) {
        throw 'The PreTag filter selected no test at all. A gate that grades nothing is not a gate.'
    }
}

task . Clean, Lint, Build, Test
