function Write-PowerShellDataFile {
    <#
    .SYNOPSIS
        Write a flat hashtable back out as a .psd1 an Import can read.
    .DESCRIPTION
        The overlay's settings and theme files are flat maps of scalars, which
        is the only shape this writes. It refuses anything else rather than
        emitting something Import-PowerShellDataFile would reject at render
        time, three stages away from the cause.

        Values are emitted by type: numbers bare, booleans as $true/$false,
        everything else single-quoted with internal quotes doubled. Writing a
        number as a string is not cosmetic - the renderer's own settings schema
        types them, and a quoted 1.25 stops being a zoom multiplier.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [string] $Path,
        [Parameter(Mandatory)] [System.Collections.IDictionary] $Data
    )

    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add('# Generated by PSGraphRenderToHtml. This is a temporary overlay of a')
    $lines.Add('# PSGraphRender backend, not that backend. Do not edit; do not commit.')
    $lines.Add('@{')

    foreach ($key in ($Data.Keys | Sort-Object)) {
        $value = $Data[$key]
        $rendered = switch ($true) {
            { $value -is [bool] } { if ($value) { '$true' } else { '$false' }; break }
            { $value -is [int] -or $value -is [long] } { [string]$value; break }
            { $value -is [double] -or $value -is [decimal] -or $value -is [single] } {
                # Invariant culture: a machine whose locale writes 1,25 emits a
                # .psd1 that parses as something else entirely.
                ([double]$value).ToString([System.Globalization.CultureInfo]::InvariantCulture); break
            }
            { $value -is [string] } { "'" + $value.Replace("'", "''") + "'"; break }
            default {
                throw "Cannot write setting '$key': this writer handles scalars only and was given [$($value.GetType().Name)]."
            }
        }
        $lines.Add(("    {0,-24} = {1}" -f $key, $rendered))
    }

    $lines.Add('}')
    Set-Content -LiteralPath $Path -Value ($lines -join [Environment]::NewLine) -Encoding utf8NoBOM
}
