function Write-PowerShellDataFile {
    <#
    .SYNOPSIS
        Write a hashtable back out as a .psd1 an Import can read.
    .DESCRIPTION
        The overlay's settings and theme files. It refuses anything it cannot
        write rather than emitting something Import-PowerShellDataFile would
        reject at render time, three stages away from the cause.

        Values are emitted by type: numbers bare, booleans as $true/$false,
        $null as $null, strings single-quoted with internal quotes doubled,
        and MAPS AND LISTS RECURSIVELY. Writing a number as a string is not
        cosmetic - the renderer's own settings schema types them, and a quoted
        1.25 stops being a zoom multiplier.

        THE NESTED CASE IS NOT DECORATION, and v0.1.0 through v0.1.1 did not
        have it. This writer emits the WHOLE merged file, not the caller's
        keys, so PSGraphRender's own theme.psd1 - which declares KindColor,
        LinkColor and EdgeResolutionStyle as maps - had to survive the round
        trip before any theme key could be applied at all. It did not: passing
        a single scalar theme override threw on EdgeResolutionStyle, a key the
        caller had never mentioned. The effect was that -Theme was unusable in
        every form, which is why nothing had noticed - a parameter nobody could
        use has no wrong behaviour to report.

        A key's value is REPLACED, not deep-merged. Handing back half of a
        caller's KindColor map and half of the backend's would be a colour
        scheme neither of them wrote.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [string] $Path,
        [Parameter(Mandatory)] [System.Collections.IDictionary] $Data
    )

    function ConvertTo-DataFileLiteral {
        <#
            One value, as .psd1 source. $Indent is the indentation the value's
            OPENING brace sits at, so a nested map closes where it started.
            $Trail names the key path for the refusal message: 'KindColor.Enum'
            says where to look, where "a hashtable" does not.
        #>
        param(
            [Parameter()] [AllowNull()] $Value,
            [Parameter(Mandatory)] [string] $Indent,
            [Parameter(Mandatory)] [string] $Trail
        )

        if ($null -eq $Value) { return '$null' }
        if ($Value -is [bool]) { return $(if ($Value) { '$true' } else { '$false' }) }
        if ($Value -is [int] -or $Value -is [long]) { return [string]$Value }
        if ($Value -is [double] -or $Value -is [decimal] -or $Value -is [single]) {
            # Invariant culture: a machine whose locale writes 1,25 emits a
            # .psd1 that parses as something else entirely.
            return ([double]$Value).ToString([System.Globalization.CultureInfo]::InvariantCulture)
        }
        if ($Value -is [string]) { return "'" + $Value.Replace("'", "''") + "'" }

        if ($Value -is [System.Collections.IDictionary]) {
            if ($Value.Count -eq 0) { return '@{}' }
            $inner = $Indent + '    '
            $parts = [System.Collections.Generic.List[string]]::new()
            $parts.Add('@{')
            foreach ($key in ($Value.Keys | Sort-Object)) {
                $literal = ConvertTo-DataFileLiteral -Value $Value[$key] -Indent $inner -Trail "$Trail.$key"
                $parts.Add(('{0}{1,-24} = {2}' -f $inner, $key, $literal))
            }
            $parts.Add($Indent + '}')
            return ($parts -join [Environment]::NewLine)
        }

        # A string is IEnumerable and was returned above; order matters here.
        if ($Value -is [System.Collections.IEnumerable]) {
            $items = @($Value)
            if ($items.Count -eq 0) { return '@()' }
            $rendered = foreach ($i in 0..($items.Count - 1)) {
                ConvertTo-DataFileLiteral -Value $items[$i] -Indent $Indent -Trail "$Trail[$i]"
            }
            return '@(' + ($rendered -join ', ') + ')'
        }

        throw "Cannot write '$Trail': this writer handles scalars, maps and lists, and was given [$($Value.GetType().Name)]."
    }

    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add('# Generated by PSGraphRenderToHtml. This is a temporary overlay of a')
    $lines.Add('# PSGraphRender backend, not that backend. Do not edit; do not commit.')
    $lines.Add('@{')

    foreach ($key in ($Data.Keys | Sort-Object)) {
        $literal = ConvertTo-DataFileLiteral -Value $Data[$key] -Indent '    ' -Trail $key
        $lines.Add(('    {0,-24} = {1}' -f $key, $literal))
    }

    $lines.Add('}')
    Set-Content -LiteralPath $Path -Value ($lines -join [Environment]::NewLine) -Encoding utf8NoBOM
}
